### ISSUE TITLE
Won't run

### ISSUE THREAD

**Issue by kyds3k** [enkille/ffxiv-rainmeter#2]
Hello,

When I try to open the FFXIV_0.7.rmskin file, I get this error:

![image](https://user-images.githubusercontent.com/1071985/150137207-0e6b3c9c-770a-420f-a717-c1ce8b13fb4e.png)

I have the latest version of RainMeter, and I downloaded the whole repo in a ZIP and extracted to a folder.

**Comment by enkille** [comment]
Unzip this one and try it, please.
[FFXIV_0.7.rmskin.zip](https://github.com/enkille/ffxiv-rainmeter/files/7898993/FFXIV_0.7.rmskin.zip)

**Comment by kyds3k** [comment]
It loads now! But all of my hard drives are listed at 0 bytes.

**Comment by enkille** [comment]
If you mean the action bar, by default it shows a list of drives but it's meant to be used for shortcut folders. They don't show the size available, but the size of the items in the folder. I could probably make it default to something that's more useful rather than having a misleading default value.

In the skin's `@Resource` folder, there is an `include.inc` file where you set the paths for your action bar buttons.
